### ISSUE TITLE
Toasterの初期化位置について

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/React-todo_Converting_JavaScript_App_To_React#3]
https://github.com/yiinuma/React-todo_Converting_JavaScript_App_To_React/blob/acb97e9c20ac37728c68117ff4875275328dc843/src/components/Modal.jsx#L107

おそらくModalコンポーネントでtoast使いたかったからModalコンポーネントに設置したかと思いますが、
App.jsxなど、最上位のコンポーネントに`Toaster`を設置するのが一般的です

呼び出すコンポーネントの階層によってtoastが使えない可能性が出てくるので💡

**Comment by yiinuma** [comment]
App.jsに移動し、他は削除しました
