### ISSUE TITLE
Modalの初期値について

### ISSUE THREAD

**Issue by mizushima1226** [yiinuma/React-todo_Converting_JavaScript_App_To_React#4]
特定のTodoの編集モーダルを開く→編集する→モーダルを閉じる→同じTodoの編集モーダルを開く
の時、編集されたままの値が入力欄にセットされています
意図通りなら良いですが、以前のモーダルの編集内容が残ってしまっているのが気になりました👀

**Comment by yiinuma** [comment]
Modalを閉じるときに編集内容を初期化します
